# Generated by Django 3.2.5 on 2021-07-12 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planetmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('planet_name', models.CharField(max_length=200)),
                ('planet_img', models.ImageField(upload_to='images/')),
                ('post', models.CharField(max_length=140)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('up_vote', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='planetmodel.body')),
            ],
        ),
        migrations.CreateModel(
            name='Planet_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=140)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('up_vote', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetpost.planet_post')),
            ],
        ),
    ]
