# Generated by Django 3.2.5 on 2021-07-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('englishName', models.CharField(max_length=255)),
                ('isPlanet', models.BooleanField()),
                ('hasMoons', models.BooleanField()),
                ('numOfMoons', models.IntegerField()),
                ('namesOfMoons', models.CharField(max_length=255)),
                ('mass', models.DecimalField(decimal_places=5, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=5, max_digits=5)),
                ('density', models.DecimalField(decimal_places=5, max_digits=5)),
                ('aroundPlanet', models.TextField()),
                ('discoveredBy', models.CharField(max_length=255)),
                ('discoveryDate', models.DateField()),
                ('axialTilt', models.DecimalField(decimal_places=5, max_digits=5)),
                ('avgTemp', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
