# Generated by Django 3.2.5 on 2021-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('englishName', models.CharField(max_length=255)),
                ('isPlanet', models.BooleanField()),
                ('mass', models.FloatField(default=1.0)),
                ('volume', models.FloatField(default=1.0)),
                ('density', models.FloatField(default=1.0)),
                ('discoveredBy', models.CharField(max_length=255)),
                ('discoveryDate', models.CharField(max_length=255)),
                ('axialTilt', models.FloatField(default=1.0)),
                ('avgTemp', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
