# Generated by Django 3.2.5 on 2021-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='avgTemp',
            field=models.DecimalField(decimal_places=12, max_digits=12),
        ),
        migrations.AlterField(
            model_name='body',
            name='axialTilt',
            field=models.DecimalField(decimal_places=12, max_digits=12),
        ),
        migrations.AlterField(
            model_name='body',
            name='density',
            field=models.DecimalField(decimal_places=12, max_digits=12),
        ),
        migrations.AlterField(
            model_name='body',
            name='volume',
            field=models.DecimalField(decimal_places=12, max_digits=12),
        ),
    ]
