# Generated by Django 3.2.5 on 2021-07-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ('name',)},
        ),
    ]
