# Generated by Django 3.2.5 on 2021-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetmodel', '0002_auto_20210709_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='aroundPlanet',
        ),
        migrations.AlterField(
            model_name='body',
            name='avgTemp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='body',
            name='axialTilt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='body',
            name='density',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='body',
            name='mass',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='body',
            name='namesOfMoons',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='body',
            name='numOfMoons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='body',
            name='volume',
            field=models.CharField(max_length=255),
        ),
    ]
