# Generated by Django 3.2.5 on 2021-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetmodel', '0003_auto_20210709_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='discoveryDate',
            field=models.CharField(max_length=255),
        ),
    ]
