# Generated by Django 3.2.5 on 2021-07-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetmodel', '0004_alter_body_discoverydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='hasMoons',
        ),
        migrations.RemoveField(
            model_name='body',
            name='namesOfMoons',
        ),
        migrations.RemoveField(
            model_name='body',
            name='numOfMoons',
        ),
    ]
