# Generated by Django 3.2.5 on 2021-07-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetmodel', '0005_auto_20210709_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='volume',
        ),
    ]
