# Generated by Django 3.2.5 on 2021-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetmodel', '0007_remove_body_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='mass',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='body',
            name='volume',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='body',
            name='avgTemp',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='body',
            name='axialTilt',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='body',
            name='density',
            field=models.FloatField(default=1.0),
        ),
    ]
